### PR TITLE
Work on a copy as recursion-context changes the arrays

### PR DESCRIPTION
**Pull request by bwoebi**
Working towards sebastianbergmann/phpunit#2361

### CODE REVIEW

**Comment by bwoebi** [comment]
I have a single failure in phpunit tests left:

```
1) Framework_ConstraintTest::testConstraintIsEqual2 with data set #15 (SplObjectStorage Object (...), SplObjectStorage Object (...), 'Failed asserting that two obj...&0\n )\n')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 -        )
+-        'inf' => null
+-    )
+-    '00000000138b29cc000000007efbdb33' => Array &1 (
 +SplObjectStorage Object &00000000138b29c2000000007efbdb33 (
 +    '00000000138b29cc000000007efbdb33' => Array &0 (
-+        'obj' => stdClass Object &00000000138b29cc000000007efbdb33 ()
+         'obj' => stdClass Object &00000000138b29cc000000007efbdb33 ()
          'inf' => null
      )
--    '00000000138b29cc000000007efbdb33' => Array &0
  )
 '

/Users/Bob/phpunit/src/Framework/Constraint/IsEqual.php:138
/Users/Bob/phpunit/src/Framework/Assert.php:2184
/Users/Bob/phpunit/src/Framework/Assert.php:513
/Users/Bob/phpunit/tests/Framework/ConstraintTest.php:989
/Users/Bob/phpunit/src/Framework/TestCase.php:1103
/Users/Bob/phpunit/src/Framework/TestCase.php:954
/Users/Bob/phpunit/src/Framework/TestResult.php:701
/Users/Bob/phpunit/src/Framework/TestCase.php:909
/Users/Bob/phpunit/src/Framework/TestSuite.php:753
/Users/Bob/phpunit/src/Framework/TestSuite.php:753
/Users/Bob/phpunit/src/Framework/TestSuite.php:753
/Users/Bob/phpunit/src/Framework/TestSuite.php:753
/Users/Bob/phpunit/src/TextUI/TestRunner.php:465
/Users/Bob/phpunit/src/TextUI/Command.php:185
/Users/Bob/phpunit/src/TextUI/Command.php:115
```

But checking it for the tenth time, I believe the **expected** value is actually wrong.

```
        $a      = new stdClass;
        $a->foo = 'bar';
        $b      = new stdClass;

        $storage1 = new SplObjectStorage;
        $storage1->attach($a);
        $storage1->attach($b);
        $storage2 = new SplObjectStorage;
        $storage2->attach($b);
```
gives
```
SplObjectStorage Object &000000007f3001bb000000006ac95985 (
    '000000007f3001a5000000006ac95985' => Array &0 (
        'obj' => stdClass Object &000000007f3001a5000000006ac95985 ()
        'inf' => null
    )
)
```
and
```
SplObjectStorage Object &000000007f3001ba000000006ac95985 (
    '000000007f3001a4000000006ac95985' => Array &0 (
        'obj' => stdClass Object &000000007f3001a4000000006ac95985 (
            'foo' => 'bar'
        )
        'inf' => null
    )
    '000000007f3001a5000000006ac95985' => Array &1 (
        'obj' => stdClass Object &000000007f3001a5000000006ac95985 ()
        'inf' => null
    )
)
```
Your expected diff is:
```
-SplObjectStorage Object &$storage1hash (
-    '$ahash' => Array &0 (
-        'obj' => stdClass Object &$ahash (
-            'foo' => 'bar'
-        )
+SplObjectStorage Object &$storage2hash (
+    '$bhash' => Array &0 (
+        'obj' => stdClass Object &$bhash ()
         'inf' => null
     )
-    '$bhash' => Array &0
 )
```
How is this line `-    '$bhash' => Array &0` even possible? There are no recursions in this structure, so this is not possible.

I think this is a bug in your original recursion-context implementation.

Can you please verify @sebastianbergmann ?

Thanks!

**Comment by sebastianbergmann** [comment]
Does "I think this is a bug in your original recursion-context implementation" mean that the bug is now gone? And do I understand correctly that due to that bug in recursion-context the expected result of this test was wrong?

**Comment by bwoebi** [comment]
Yes, you understood it correctly.

You need to fix this in the phpunit testsuite.

**Comment by sebastianbergmann** [comment]
Thanks, moved to https://github.com/sebastianbergmann/phpunit/issues/2364

**Pull request merged**
